---
- hosts: r13
  become: yes
  gather_facts: false
  vars:
    - eigrp: 0 
  tasks: 
  - name: Test Connection
    ios_command:
      commands:
        - show clock
        - show ip int br
    tags:
      - show commnad


  - name: loopback
    ios_config:
      lines:
        - ip addres 13.13.13.13 255.255.255.255
        - no shut 
      parents: interface  loop 0
  - name: Interface config
    ios_config:
      lines:
        - ip addres 191.168.1.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/3
    tags:
      - fast 0/1 

  - name: Interface config
    ios_config:
      lines:
        - ip addres 191.168.3.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 1/1
    tags:
      - config fast 0/2

  - name: Interface config
    ios_config:
      lines:
        - ip addres 191.168.4.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 1/2

  - name: Interface config
    ios_config:
      lines:
        - ip addre 191.168.2.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 1/0
  - name: config eigrp
    ios_config: 
      lines:
         - no network 10.10.10.101 255.255.255.0
         - no network 10.10.10.91 255.255.255.0
         -  network 191.168.1.2 255.255.255.0
         -  network 191.168.3.2 255.255.255.0
      parents: router eigrp 1 
      ####
      
  - name: config ospf
    ios_config: 
      lines:
        - no network 20.20.20.91 0.0.0.255 area 0
        - no network 20.20.20.101 0.0.0.255 area 0
        -  network 191.168.4.2 0.0.0.255 area 0
        -  network 191.168.2.2 0.0.0.255 area 0
      parents: router ospf 1 
      ## #################
  - name: save config
    ios_command:
      commands:
        - wr
