- name:  Install docker if its not already
  shell: |
    apt install docker.io
    apt install docker-engine
    apt install docker-ce
  when: "'docker-ce' not in ansible_facts.packages"
  become: true
- name: Print something useful if it is already installed
  debug:
    msg: "Docker already installed."
  when: "'docker-ce' in ansible_facts.packages"
- name: Add the user to docker group
  ansible.builtin.user:
    name: amir
    uid: 1000
    group: docker
    append: yes
