---
- hosts: r6
  become: yes
  gather_facts: false
  vars:
    - bgp_asnumber_65000: 65000
    - bgp_asnumber_65002: 65002
    - bgp_asnumber_65003: 65003
    - bgp_asnumber_65004: 65004
  tasks: 
  - name: Test Connection
    ios_command:
      commands:
        - show clock
        - show ip int br
    tags:
      - bgp

  - name: BGP Config
    ios_config:
      lines:
        - neighbor 4.4.4.4 remote-as {{ bgp_asnumber_65000 }}
        - neighbor 4.4.4.4 update-source loopback 0
        - neighbor 4.4.4.4 ebgp-multihop 
        - neighbor 2.2.2.2 remote-as {{ bgp_asnumber_65000 }}
        - neighbor 2.2.2.2 update-source loopback 0
        - neighbor 2.2.2.2 ebgp-multihop 
        - neighbor 7.7.7.7 remote-as {{ bgp_asnumber_65003 }}
        - neighbor 7.7.7.7 update-source loopback 0
        - neighbor 7.7.7.7 ebgp-multihop 
        - neighbor 8.8.8.8 remote-as {{ bgp_asnumber_65004 }}
        - neighbor 8.8.8.8 update-source loopback 0
        - neighbor 8.8.8.8 ebgp-multihop 
      parents: router bgp 65001
    tags:
      - bgp


  - name: loopback
    ios_config:
      lines:
        - ip addres 6.6.6.6 255.255.255.255
        - no shut 
      parents: interface  loop 0
  - name: Interface config
    ios_config:
      lines:
        - ip addres 192.168.3.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/2
    tags:
      - config 

  - name: Interface config
    ios_config:
      lines:
        - ip addres 192.168.7.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/1
    tags:
      - config 

  - name: Interface config
    ios_config:
      lines:
        - ip addres 172.16.3.1 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/3

  - name: Interface config
    ios_config:
      lines:
        - ip addres 172.16.4.1 255.255.255.0
        - no shut 
      parents: interface  Ethernet 1/0
  - name: Interface config
    ios_config:
      lines:
        - ip addres 192.168.7.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/1
    tags:
      - config 
  - name: static route
    ios_config:
      lines:
        - ip route 4.4.4.4 255.255.255.255 192.168.7.1
        - ip route 7.7.7.7 255.255.255.255 172.16.3.2
        - ip route 2.2.2.2 255.255.255.255 192.168.3.1
        - ip route 8.8.8.8 255.255.255.255 192.16.4.1
  - name: Interface config
    ios_config:
      lines:
        - ip addres 192.168.7.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/1
    tags:
      - config 
    tags:
      - config 
  - name: save config
    ios_command:
      commands:
        - wr
        - show ip int br
