---
- hosts: localhost
  become: true
  vars: 
     package: ssh
     package_state: reloaded
  tasks:
  - name:
    service:
      name: "{{ package }}"
      state: "{{ package_state }}"
    register: package


  - debug:
      var: package
