---
- hosts: all
  become: true
  tasks:
  - name: install terraform to ubuntu
    tags: tera
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.0.4/terraform_1.0.4_linux_amd64.zip 
      dest: /sbin
      remote_src: yes
      mode: 755
      owner: root
  pre_tasks:
  - name: install unzip
    apt:
     name: unzip
    
