---
- hosts: r1
  become: yes
  gather_facts: false
  vars:
    - bgp_asnumber_65001: 65001
    - bgp_asnumber_65002: 65002
  tasks: 
  - name: Test Connection
    ios_command:
      commands:
        - show clock
        - show ip int br
    tags:
      - show commnad

  - name: BGP Config
    ios_config:
      lines:
         - neighbor 5.5.5.5 remote-as {{ bgp_asnumber_65001 }}
         - neighbor 5.5.5.5.5 update-source loopback 0
         - neighbor 5.5.5.5 ebgp-multihop
         - neighbor 9.9.9.9 remote-as {{ bgp_asnumber_65002 }}
         - neighbor 9.9.9.9 update-source loopback 0
         - neighbor 9.9.9.9 ebgp-multihop
      parents: router bgp 65000
    tags:
       - bgp


  - name: loopback
    ios_config:
      lines:
        - ip addres 1.1.1.1 255.255.255.255
        - no shut 
      parents: interface  loop 0
  - name: Interface config
    ios_config:
      lines:
        - ip addres 192.168.1.1 255.255.255.0
        - no shut 
      parents: interface ether 0/1
  - name: static route
    ios_config:
      lines:
        - ip route 5.5.5.5 255.255.255.255 192.168.1.2
        - ip route 9.9.9.9 255.255.255.255 192.168.2.2
    tags:
      - static 

  - name: Interface config
    ios_config:
      lines:
        - ip addres 192.168.2.1 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/2
    tags:
      - config
  - name: save config
    ios_command:
       commands:
          - wr  
