---
- hosts: r3
  become: yes
  gather_facts: false
  vars:
    - ospf_no: 2
    - bgp_asnumber_65001: 65001
    - bgp_asnumber_65002: 65002
  tasks: 

  - name: Test Connection
    ios_command:
      commands:
        - show clock
        - show ip int br
    tags:
      - showfile

  - name: bgp configuratin
    ios_config:
      lines:
        - neighbor 5.5.5.5 remote-as {{ bgp_asnumber_65001 }}
        - neighbor 5.5.5.5 update-source loopback 0 
        - neighbor 5.5.5.5 ebgp-multihop 
        - neighbor 9.9.9.9 remote-as {{ bgp_asnumber_65002 }}
        - neighbor 9.9.9.9 update-source loopback 0 
        - neighbor 9.9.9.9 ebgp-multihop 
      parents: router bgp 65000
    tags:
      - bgp
  - name: config ip address
    ios_config:
      lines:
        - ip addres 192.168.5.1 255.255.255.0
        - no shut 
      parents: interface  Ethernet 1/0
    tags:
      - config 

  - name: Interface config
    ios_config:
      lines:
        - ip addres 192.168.6.1 255.255.255.0
        - no shut 
      parents: interface  Ethernet 1/1
    tags:
      - config 
  - name: config ip address
    ios_config:
      lines:
        - ip addres 3.3.3.3  255.255.255.255
        - no shut 
      parents: interface  loop 0
  - name: static
    ios_config:
      lines:
        -  ip route 5.5.5.5 255.255.255.255 192.168.5.2 
        -  ip route 9.9.9.9 255.255.255.255 192.168.6.2 

  - name: Test Connection
    ios_command:
      commands:
        - wr
        - show ip int br
    tags:
      - save 
