---
- hosts: r6
  become: yes
  gather_facts: false
  vars:
    - ospf_no: 2
    - bgp_asnumber_65000: 65000
      # - bgp_asnumer_65002: 65002
  tasks: 
  - name: Test Connection
    ios_command:
      commands:
        - show clock
        - show ip int br
    tags:
      - bgp

  - name: BGP Config
    ios_config:
      lines:
       - network 6.6.6.6
       - neighbor 6.6.6.6 remote-as {{ bgp_asnumber_65000 }}
         # - neighbor 10.10.2.2 remote-as {{ bgp_asnumer_65002 }}
       - neighbor 2.2.2.2 remote-as {{ bgp_asnumber_65000 }}
       - neighbor 4.4.4.4 remote-as {{ bgp_asnumber_65000 }}
      parents: router bgp 65000
    tags:
      - bgp


  - name: loopback
    ios_config:
      lines:
        - ip addres 6.6.6.6 255.255.255.255
        - no shut 
      parents: interface  loop 0
  - name: Interface config
    ios_config:
      lines:
        - ip addres 10.10.3.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/2
    tags:
      - config 

  - name: Interface config
    ios_config:
      lines:
        - ip addres 10.10.7.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/1
    tags:
      - config 
  - name: save config
    ios_command:
      commands:
        - wr
        - show ip int br
