---
- hosts: r12
  become: yes
  gather_facts: false
  vars:
    - ospf_no: 2
    - bgp_asnumber_65002: 65002
  tasks: 
  - name: Test Connection
    ios_command:
      commands:
        - show clock
        - show ip int br

  - name: BGP Config
    ios_config:
     lines:
       - neighbor 10.10.10.10 remote-as {{ bgp_asnumber_65002 }}
       - neighbor 10.10.10.10 update-source loopback 0
       - neighbor 10.10.10.10 ebgp-
       - neighbor 9.9.9.9 remote-as {{ bgp_asnumber_65002 }}
       - neighbor 9.9.9.9 update-source loopback 0
       - neighbor 9.9.9.9 ebgp-
     parents: router bgp 65006
    tags:
      - bgp


  - name: loopback
    ios_config:
      lines:
        - ip addres 12.12.12.12 255.255.255.255
        - no shut 
      parents: interface  loop 0
  - name: Interface config
    ios_config:
      lines:
        - ip addres 172.16.6.2 255.255.255.0 
        - no shut 
      parents: interface  Ethernet 0/1
    tags:
      - config 

  - name: Ip route
    ios_config:
      lines:
        - ip route 9.9.9.9 255.255.255.255 172.16.6.1
        - ip route 10.10.10.10 255.255.255.255 172.16.8.1
  - name: Interface config
    ios_config:
      lines:
        - ip addres 172.16.8.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 1/2
    tags:
      - config 
  - name: save config
    ios_command:
      commands:
        - wr
        - show ip int br
        - show ip route
