---
- hosts: r1
  become: yes
  gather_facts: false
  vars:
    ifs:
      if3:
        name: "0/3"
        address: "10.10.1.1"
        mask: "255.255.255.0"      
        type: "Ethernet"

      lo:
        name: "0"
        address: "1.1.1.1"
        mask: "255.255.255.255"      
        type: "loop"
   
    
  tasks: 
  - name: Interface config
    ios_config:
      lines:
        - ip addres {{ item.value.address }} {{ item.value.mask }}
        - no shut 
      parents: interface  {{ item.value.type }} {{ item.value.name }}
    loop: "{{ lookup('dict', ifs) }}"
    notify:
      - save config
    loop: "{{ lookup('dict', ifs) }}"
    notify:
      - save config

  - name: Test Connection
    ios_config:
      lines: "{item.test.yml}""
        
   
      befor:  "no ip osp 1"
      parents: router ospf 1
    tags:
      - ospf
  handlers:
  - name: save config
    ios_command:
      commands:
        - wr
  - name: sho ip ospf neighbor
    ios_command:
      commands:
        - show ip ospf neighbor
