---
- hosts: r3
  become: yes
  gather_facts: false
  vars:
    ifs:
      if3:
        name: "0/3"
        address: "10.10.1.2"
        mask: "255.255.255.0"      
        type: "Ethernet"

      if1/0:
        name: "1/0"
        address: "10.10.7.1"
        mask: "255.255.255.0"      
        type: "Ethernet"
      if1/1:
        name: "1/1"
        address: "10.10.2.2"
        mask: "255.255.255.0"      
        type: "Ethernet"
      if0/1:
        name: "0/1"
        address: "10.10.3.1"
        mask: "255.255.255.0"      
        type: "Ethernet"
      if0/2:
        name: "0/2"
        address: "10.10.6.1"
        mask: "255.255.255.0"      
        type: "Ethernet"
      lo:
        name: "0"
        address: "3.3.3.3"
        mask: "255.255.255.255"      
        type: "loop"
   
    
  tasks: 
  - name: Interface config
    ios_config:
      lines:
        - ip addres {{ item.value.address }} {{ item.value.mask }}
        - no shut 
      parents: interface  {{ item.value.type }} {{ item.value.name }}
    loop: "{{ lookup('dict', ifs) }}"
    notify:
      - save config
    loop: "{{ lookup('dict', ifs) }}"
    notify:
      - save config

  - name: Test Connection
    ios_config:
      lines:
        - network 10.10.7.1 0.0.0.255 area 0
        - network 10.10.2.2 0.0.0.255 area 2
        - network 10.10.1.2 0.0.0.255 area 1
        - network 10.10.6.1 0.0.0.255 area 0
        - network 10.10.3.1 0.0.0.255 area 0
        - network 3.3.3.3 0.0.0.0 area 0
      parents: router ospf 1
    tags:
      - show commnad
  handlers:
  - name: save config
    ios_command:
      commands:
        - wr
