---
- hosts: r9
  become: yes
  gather_facts: false
  vars:
    ifs:
      if3:
        name: "0/1"
        address: "10.10.14.2"
        mask: "255.255.255.0"
        type: "Ethernet"      
    ifs:
      if3:
        name: "1/1"
        address: "10.10.12.2"
        mask: "255.255.255.0"
        type: "Ethernet"      
      lo:
       name: "0"
       address: "9.9.9.9"
       mask: "255.255.255.255"      
       type: "loop"
   
    
  tasks: 
  - name: Interface config
    ios_config:
      lines:
        - ip addres {{ item.value.address }} {{ item.value.mask }}
        - no shut 
      parents: interface  {{ item.value.type }} {{ item.value.name }}
    loop: "{{ lookup('dict', ifs) }}"
    notify:
      - save config
    loop: "{{ lookup('dict', ifs) }}"
    notify:
      - save config

  - name: Test Connection
    ios_config:
      lines:
        - network 10.10.12.2 0.0.0.255 area 4
        - network 10.10.14.2 0.0.0.255 area 4
        - network 9.9.9.9 0.0.0.0 area 4
      parents: router ospf 1
    tags:
      - show commnad
  handlers:
  - name: save config
    ios_command:
      commands:
        - wr
