---
- hosts: r10
  become: yes
  gather_facts: false
  vars:
    - bgp_asnumber_65000: 65000
    - bgp_asnumber_65005: 65005
    - bgp_asnumber_65006: 65006
  tasks: 
  - name: Test Connection
    ios_command:
      commands:
        - show clock
        - show ip int br
    tags:
      - bgp

  tasks:
  - name: BGP Config
    ios_config:
      lines:
        - neighbor 2.2.2.2 remote-as {{ bgp_asnumber_65000 }}
        - neighbor 2.2.2.2 update-source loopback0
        - neighbor 2.2.2.2 ebgp-multi
        - neighbor 4.4.4.4 remote-as {{ bgp_asnumber_65000 }}
        - neighbor 4.4.4.4 update-source loopback0
        - neighbor 4.4.4.4 ebgp-multihop
        - neighbor 11.11.11.11 remote-as {{ bgp_asnumber_65005 }}
        - neighbor 11.11.11.11 update-source loopback 0
        - neighbor 11.11.11.11 ebgp-multihop
        - neighbor 12.12.12.12 remote-as {{ bgp_asnumber_65006 }}
        - neighbor 12.12.12.12 update-source loopback 0
        - neighbor 12.12.12.12 ebgp-multihop
      parents: router bgp 65002
    tags:
      - bgp


  - name: loopback
    ios_config:
      lines:
        - ip addres 10.10.10.10 255.255.255.255
        - no shut 
      parents: interface  loop 0

  - name: Interface config
    ios_config:
      lines:
        - ip addres 192.168.4.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/3
    tags:
      - config 

       
  - name: Interface config
    ios_config:
      lines:
        - ip addres 172.16.7.1 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/2

  - name: Interface config
    ios_config:
      lines:
        - ip addres 192.168.8.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 1/0
  - name: static route
    ios_config:
      lines:
        - ip route 2.2.2.2 255.255.255.255 192.168.4.1 
        - ip route 4.4.4.4 255.255.255.255 192.168.8.1 
        - ip route 11.11.11.11 255.255.255.255 172.16.7.2     
        - ip route 12.12.12.12 255.255.255.255 172.16.8.2     
  - name: Interface config
    ios_config:
      lines:
        - ip addres 172.16.8.1 255.255.255.0
        - no shut 
      parents: interface  Ethernet 1/2
    tags:
      - config 
  - name: save config
    ios_command:
      commands:
        - wr
        - show ip int br
        - sho ip route

