---
- hosts: r9
  become: yes
  gather_facts: false
  vars:
    - ospf_no: 2
    - bgp_asnumber_65000: 65000
    - bgp_asnumer_65002: 65005 
    - bgp_asnumer_65002: 65006 
  tasks: 
  - name: Test Connection
    ios_command:
      commands:
        - show clock
        - show ip int br

  - name: BGP Config
    ios_config:
      lines:
        - neighbor 1.1.1.1 remote-as {{ bgp_asnumber_65000 }}
        - neighbor 1.1.1.1 update-source loopback 0
        - neighbor 1.1.1.1 ebgp-multihop
        - neighbor 3.3.3.3 remote-as {{ bgp_asnumber_65000 }}
        - neighbor 3.3.3.3 update-source loopback 0
        - neighbor 3.3.3.3 ebgp-multihop
        - neighbor 11.11.11.11 remote-as {{ bgp_asnumer_65005 }}
        - neighbor 11.11.11.11 update-source loopback 0
        - neighbor 11.11.11.11 ebgp-multihop
        - neighbor 12.12.12.12.12 remote-as {{ bgp_asnumer_65006 }}
        - neighbor 12.12.12.12 update-source loopback 0
        - neighbor 12.12.12.12 ebgp-multihop
      parents: router bgp 65002

  tasks:
  - name: loopback
    ios_config:
      lines:
        - ip addres 9.9.9.9 255.255.255.255
        - no shut 
      parents: interface  loop 0
  - name: Interface config
    ios_config:
      lines:
        - ip addres 192.168.6.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 1/1
    tags:
      - config 

  - name: Interface config
    ios_config:
      lines:
        - ip addres 192.168.2.2 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/2
    tags:
      - config 
  - name: Interface config
    ios_config:
      lines:
        - ip addres 172.16.5.1 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/3
  - name: bgp
    ios_config:
      lines:
        - ip route 1.1.1.1 255.255.255.255 192.168.2.1
        - ip route 3.3.3.3 255.255.255.255 192.168.6.1
        - ip route 11.11.11.11 255.255.255.255 172.16.5.2
        - ip route 12.12.12.12 255.255.255.255 172.16.6.1
  - name: interface
    ios_config:
      lines:
        - ip addres 172.16.6.1 255.255.255.0
        - no shut 
      parents: interface  Ethernet 0/1
  - name: save config
    ios_command:
      commands:
        - wr
        - show ip int br
