---
- hosts: core2 
  become: yes
  gather_facts: false
  vars:
    ifs:
      if1:
        name: "1/0"
        address: "20.20.1.1"
        mask: "255.255.255.0"      
        type: "Ethernet"
      if2:
        name: "0/1"
        address: "20.20.2.1"
        mask: "255.255.255.0"      
        type: "Ethernet"
      if3:
        name: "1/1"
        address: "20.20.3.1"
        mask: "255.255.255.0"      
        type: "Ethernet"
      if4:
        name: "2/2"
        address: "20.20.4.1"
        mask: "255.255.255.0"      
        type: "Ethernet"
      if5:
        name: "1/3"
        address: "20.20.5.1"
        mask: "255.255.255.0"      
        type: "Ethernet"
      if6:
        name: "2/3"
        address: "20.20.6.1"
        mask: "255.255.255.0"      
        type: "Ethernet"
      if7:
        name: "2/1"
        address: "20.20.7.1"
        mask: "255.255.255.0"      
        type: "Ethernet"
      if8:
        name: "3/0"
        address: "20.20.8.1"
        mask: "255.255.255.0"      
        type: "Ethernet"
      lo:
        name: "0"
        address: "2.2.2.2"
        mask: "255.255.255.0"      
        type: "loop"
   
  tasks: 
  - debug:
      msg: "key = {{ item.key }}ifname = {{ item.value.name }} addr = {{ item.value.address }} mask = {{ item.value.mask }} type = {{ item.value.type }}"
    loop: "{{ lookup('dict', ifs) }}"

    
  - name: Interface config
    ios_config:
      lines:
        - ip addres {{ item.value.address }} {{ item.value.mask }}
        - no shut 
      parents: interface  {{ item.value.type }} {{ item.value.name }}
    loop: "{{ lookup('dict', ifs) }}"
    notify:
      - save config

    loop: "{{ lookup('dict', ifs) }}"
    notify:
      - save config
  - name: Test Connection
    ios_command:
      commands:
        - show clock
        - show ip int br
    tags:
      - show commnad
  handlers:
  - name: save config
    ios_command:
      commands:
        - wr
