---
- hosts: all 
  become: true
  tasks:
  - name: install jcal
    apt: name=ntp   state=latest
  - shell: sleep 15 
  - name: ensure the install ntp
    service:
      name: ntp
      state: started
