---
- hosts: mls2 
  become: yes
  gather_facts: false
         
  tasks:
  - name:
    ios_config:
      lines:
        - switchport trunk encapsulation dot1q
        - switchport mode trunk
      parents: interface ethernet 0/1
  - name:
    ios_config:
      lines:
        - switchport trunk encapsulation dot1q
        - switchport mode trunk
      parents: interface ethernet 0/2
  - name:
    ios_config:
      lines:
        - vtp mode server
        - vtp version 2
        - vtp domain m
   
  - name:
    ios_config:
      lines:
        - ip address 10.1.1.1 255.255.255.0 
        - switchport mode trunk
